/**
 * Shipped demo sample (issue #193): the synthetic capture behind the
 * homepage "Test fvf • viewer with a 100k sample synthetic capture" action.
 *
 * The asset is a deterministic synthetic-mirror `.fvf` stream (no
 * instrument data) generated by `cargo run -p fvf-wasm --example synth
 * -- --sample` and committed at `apps/web/public/samples/`. The
 * `sample_asset` Rust test fails the build on any drift between the
 * committed bytes and the synthesizer.
 *
 * The `.bin` suffix keeps the workspace-wide `*.fvf` gitignore guard for
 * empirical captures intact while still serving the asset at a stable
 * URL; the app presents it to the parse pipeline under the `.fvf` display
 * name below.
 */

/** Same-origin URL of the committed sample asset (served from `public/`). */
export const SAMPLE_CAPTURE_URL = "/samples/fvf-sample.fvf.bin";

/** File name shown in the metadata banner once the sample is loaded. */
export const SAMPLE_CAPTURE_FILE_NAME = "fvf-sample.fvf";
